MODEL_TYPE: 'cnn' # 'rnn', 'cnn', 'rcnn'
DATA_DIM: '2d' # '1d', '2d'
WAVELET: False
NUM_CLASSES: 4

ARCH_TYPE: 'VGG' # 'LSTM', 'GRU', 'VGG', Inception', 'RCNN'
HIDDEN_DIM: 512
FC_DIM: 1024
NUM_LAYERS: 2
ATTENTION: ''

TEST_SPLIT: 'orig' # 'orig', '7000', '12000'
BATCH_SIZE: 256