MODEL_TYPE: 'rnn' # 'rnn', 'cnn', 'rcnn'

DATA_DIM: '1d' # '1d', '2d'

ARCH_TYPE: 'LSTM' # 'LSTM', 'GRU', 'VGG1', 'VGG2', 'Inception', 'RCNN'

TEST_SPLIT: 'orig' # 'orig', '7000', '12000'

WAVELET: False

BATCH_SIZE: 256